[build]
  publish = "frontend"
  functions = "frontend/netlify/functions"

[build.environment]
  BACKEND_URL = "https://leaderboard-api-0ej6.onrender.com"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api-proxy/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
